### PR TITLE
YouTube Clone

### PR DESCRIPTION
**Pull request by pyven**
Finished the project

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
## Hi @pyven  and @RichardBongani  :wave: 
**Great work so far,**
Before we give this a :+1: , there are a couple of things we need to fix:
1. Your code contains errors. Upload your code to [w3 validator](https://validator.w3.org/#validate_by_uri) and correct all the errors.
2. We need to fix the styles for suggested video section. Make sure the section occupies all the width left by the main video section and we have a small margin between them. 
3. Add all your styles to `styles.css` files. You have used a lot of `width` and `height` attributes in your html file.
4. Add a descriptive README file. 
5. Give this Pull Request a title and a description which is a summary of the accomplished tasks.

**After implementing the changes, submit another request for review**
_Good luck :)_

**Comment by pyven** [comment]
Fixed the errors that the w3 validator showed us and the styles for the suggested videos and added all the syles in the style.css file as well.

**Comment by RichardBongani** [comment]
We finished our video embedding project. It contains several suggested videos, subscribers and viewers icons, it contains the main video selected by the user and has links to more information.
It also has the account holders image and user name.

**Review by Ispirett — APPROVED** [review]
Great work with this project  and changes made folks 
image
You can merge this project now

*Note*
You can always come back and polish this project up when you learn more css and html

**Pull request merged**
